### PR TITLE
Implement insert_batch as described in docs

### PR DESCRIPTION
**Pull request by Flamenco**
This is already implemented in the mysql driver...

### CODE REVIEW

**Comment by kylefarris** [comment]
Thanks for the PR. I'll get this patched in ASAP.

**Comment by kylefarris** [comment]
I'm hoping to have v2 out on August 15th.

**Comment by kylefarris** [comment]
@Flamenco The code is being heavily-refactored to use ES2017 class syntax. You can see the progress being made (and the new code structure) if you look at the v2 branch.

**Comment by Flamenco** [comment]
Closing this as it is fixed in v2

**Pull request closed without merging**
